name: Test

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.28.0
      - run: "terraform init"
      - run: "terraform plan -out plan.tfplan"
      - run: "tfcmt plan -- terraform show plan.tfplan"
